<?php
namespace Woox\Webman\Jwt\Tests;

use Woox\WebmanJwt\JwtToken;

class JwtTokenTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function generateToken(): void
    {
        $user = [
            'id'  => 2024,
            'name'  => 'codeloving',
            'email' => 'codeloving@163.com'
        ];
        $token = JwtToken::generateToken($user);
        self::assertIsArray($token);
    }
}